// Code generated by l10n4x-toolkit. DO NOT EDIT.
package i18n

/*
#cgo LDFLAGS: -L. -ll10n4c -ldl -lpthread
#include <stdlib.h>
#include <stdbool.h>

bool l10n4c_set_encryption_key(const unsigned char* key, size_t key_len);
bool l10n4c_set_fallback_locale(const char* locale);
bool l10n4c_load_pak_locale(const char* locale, const char* file_path);
char* l10n4c_translate_with_params(const char* locale, const char* key, const char* params_json);
void l10n4c_free_string(char* ptr);
void l10n4c_clear();
*/
import "C"
import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"unsafe"
)

var (
	loadedLocales = make(map[string]bool)
	mu            sync.RWMutex
	initialized   sync.Once
	fallback      = "en"
	languagesDir  = "./dist/locales"
	keyEnvName    = "L10N4X_KEY"
)

// Init initializes the l10n4x runtime by configuring the encryption key and fallback locale.
func Init(fallbackLocale string, dir string, keyEnv string) {
	initialized.Do(func() {
		fallback = fallbackLocale
		languagesDir = dir
		keyEnvName = keyEnv

		keyStr := os.Getenv(keyEnvName)
		if keyStr == "" {
			fmt.Fprintf(os.Stderr, "Warning: Environment variable %s is not set. Localization FFI might fail.\n", keyEnvName)
		} else {
			keyBytes := []byte(keyStr)
			if len(keyBytes) == 32 {
				C.l10n4c_set_encryption_key((*C.uchar)(&keyBytes[0]), C.size_t(len(keyBytes)))
			} else {
				fmt.Fprintf(os.Stderr, "Error: Encryption key in %s must be exactly 32 bytes.\n", keyEnvName)
			}
		}

		cFallback := C.CString(fallback)
		defer C.free(unsafe.Pointer(cFallback))
		C.l10n4c_set_fallback_locale(cFallback)

		// Load fallback locale immediately
		loadLocale(fallback)
	})
}

func loadLocale(locale string) bool {
	mu.Lock()
	defer mu.Unlock()

	if loadedLocales[locale] {
		return true
	}

	pakPath := filepath.Join(languagesDir, locale+".pak")
	if _, err := os.Stat(pakPath); os.IsNotExist(err) {
		currentDir := languagesDir
		for i := 0; i < 6; i++ {
			testPath := filepath.Join(currentDir, locale+".pak")
			if _, statErr := os.Stat(testPath); statErr == nil {
				pakPath = testPath
				break
			}
			currentDir = filepath.Join("..", currentDir)
		}
	}

	cLocale := C.CString(locale)
	defer C.free(unsafe.Pointer(cLocale))
	cPath := C.CString(pakPath)
	defer C.free(unsafe.Pointer(cPath))

	success := bool(C.l10n4c_load_pak_locale(cLocale, cPath))
	if success {
		loadedLocales[locale] = true
	}
	return success
}

// T translates a key in the given locale, lazily loading the pak file if not already in memory.
// Optional parameters can be passed as a map[string]string.
func T(locale string, key Key, params ...map[string]string) string {
	Init(fallback, languagesDir, keyEnvName)

	locale = strings.ToLower(strings.TrimSpace(locale))
	if locale == "" {
		locale = fallback
	}

	mu.RLock()
	loaded := loadedLocales[locale]
	mu.RUnlock()

	if !loaded {
		if !loadLocale(locale) {
			mu.RLock()
			fallbackLoaded := loadedLocales[fallback]
			mu.RUnlock()
			if !fallbackLoaded {
				loadLocale(fallback)
			}
		}
	}

	cLocale := C.CString(locale)
	defer C.free(unsafe.Pointer(cLocale))
	cKey := C.CString(string(key))
	defer C.free(unsafe.Pointer(cKey))

	var cParams *C.char
	if len(params) > 0 && params[0] != nil {
		jsonBytes, err := json.Marshal(params[0])
		if err == nil {
			cParams = C.CString(string(jsonBytes))
			defer C.free(unsafe.Pointer(cParams))
		}
	}

	ptr := C.l10n4c_translate_with_params(cLocale, cKey, cParams)
	if ptr == nil {
		return string(key)
	}
	defer C.l10n4c_free_string(ptr)

	return C.GoString(ptr)
}

// Clear releases all loaded translations from memory.
func Clear() {
	mu.Lock()
	defer mu.Unlock()
	C.l10n4c_clear()
	loadedLocales = make(map[string]bool)
}
