// Code generated by l10n4x-toolkit. DO NOT EDIT.
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dart:io';
import 'package:ffi/ffi.dart';
import 'package:flutter/services.dart' show rootBundle;

abstract final class L10nKeys {
{{KEY_DEFINITIONS}}
}

typedef l10n4c_set_encryption_key_func = ffi.Bool Function(ffi.Pointer<ffi.Uint8> key, ffi.Size key_len);
typedef L10n4cSetEncryptionKey = bool Function(ffi.Pointer<ffi.Uint8> key, int key_len);

typedef l10n4c_set_fallback_locale_func = ffi.Bool Function(ffi.Pointer<Utf8> locale);
typedef L10n4cSetFallbackLocale = bool Function(ffi.Pointer<Utf8> locale);

typedef l10n4c_load_pak_locale_func = ffi.Bool Function(ffi.Pointer<Utf8> locale, ffi.Pointer<Utf8> file_path);
typedef L10n4cLoadPakLocale = bool Function(ffi.Pointer<Utf8> locale, ffi.Pointer<Utf8> file_path);

typedef l10n4c_translate_with_params_func = ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> locale, ffi.Pointer<Utf8> key, ffi.Pointer<Utf8> params_json);
typedef L10n4cTranslateWithParams = ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> locale, ffi.Pointer<Utf8> key, ffi.Pointer<Utf8> params_json);

typedef l10n4c_free_string_func = ffi.Void Function(ffi.Pointer<Utf8> ptr);
typedef L10n4cFreeString = void Function(ffi.Pointer<Utf8> ptr);

typedef l10n4c_clear_func = ffi.Void Function();
typedef L10n4cClear = void Function();

class L10n {
  static late final ffi.DynamicLibrary _lib;
  static late final L10n4cSetEncryptionKey _setEncryptionKey;
  static late final L10n4cSetFallbackLocale _setFallbackLocale;
  static late final L10n4cLoadPakLocale _loadPakLocale;
  static late final L10n4cTranslateWithParams _translateWithParams;
  static late final L10n4cFreeString _freeString;
  static late final L10n4cClear _clear;

  static bool _initialized = false;
  static final Set<String> _loadedLocales = {};
  static String _fallback = '{{FALLBACK_LOCALE}}';
  static String _languagesDir = '{{OUTPUT_DIR}}';
  static String _keyEnvName = '{{KEY_ENV}}';

  static void init({String? fallbackLocale, String? dir, String? encryptionKey}) {
    if (_initialized) return;

    if (Platform.isAndroid) {
      _lib = ffi.DynamicLibrary.open('libl10n4c.so');
    } else if (Platform.isIOS || Platform.isMacOS) {
      _lib = ffi.DynamicLibrary.process();
    } else if (Platform.isLinux) {
      _lib = ffi.DynamicLibrary.open('libl10n4c.so');
    } else if (Platform.isWindows) {
      _lib = ffi.DynamicLibrary.open('l10n4c.dll');
    } else {
      throw UnsupportedError('Unsupported platform');
    }

    _setEncryptionKey = _lib.lookup<ffi.NativeFunction<l10n4c_set_encryption_key_func>>('l10n4c_set_encryption_key').asFunction();
    _setFallbackLocale = _lib.lookup<ffi.NativeFunction<l10n4c_set_fallback_locale_func>>('l10n4c_set_fallback_locale').asFunction();
    _loadPakLocale = _lib.lookup<ffi.NativeFunction<l10n4c_load_pak_locale_func>>('l10n4c_load_pak_locale').asFunction();
    _translateWithParams = _lib.lookup<ffi.NativeFunction<l10n4c_translate_with_params_func>>('l10n4c_translate_with_params').asFunction();
    _freeString = _lib.lookup<ffi.NativeFunction<l10n4c_free_string_func>>('l10n4c_free_string').asFunction();
    _clear = _lib.lookup<ffi.NativeFunction<l10n4c_clear_func>>('l10n4c_clear').asFunction();

    _fallback = fallbackLocale ?? _fallback;
    _languagesDir = dir ?? _languagesDir;

    final key = encryptionKey ?? Platform.environment[_keyEnvName];
    if (key != null) {
      final keyBytes = utf8.encode(key);
      if (keyBytes.length == 32) {
        final ffi.Pointer<ffi.Uint8> keyPtr = calloc<ffi.Uint8>(32);
        for (var i = 0; i < 32; i++) {
          keyPtr[i] = keyBytes[i];
        }
        _setEncryptionKey(keyPtr, 32);
        calloc.free(keyPtr);
      }
    }

    final cFallback = _fallback.toNativeUtf8();
    _setFallbackLocale(cFallback);
    calloc.free(cFallback);

    _initialized = true;
    loadLocale(_fallback);
  }

  static Future<bool> loadLocale(String locale) async {
    if (!_initialized) return false;
    if (_loadedLocales.contains(locale)) return true;

    try {
      final pakPath = '$_languagesDir/$locale.pak';
      final file = File(pakPath);
      if (await file.exists()) {
        final cLocale = locale.toNativeUtf8();
        final cPath = pakPath.toNativeUtf8();
        final success = _loadPakLocale(cLocale, cPath);
        calloc.free(cLocale);
        calloc.free(cPath);
        if (success) {
          _loadedLocales.add(locale);
          return true;
        }
      } else {
        try {
          final byteData = await rootBundle.load('assets/locales/$locale.pak');
          final tempDir = await Directory.systemTemp.createTemp();
          final tempFile = File('${tempDir.path}/$locale.pak');
          await tempFile.writeAsBytes(byteData.buffer.asUint8List());

          final cLocale = locale.toNativeUtf8();
          final cPath = tempFile.path.toNativeUtf8();
          final success = _loadPakLocale(cLocale, cPath);
          calloc.free(cLocale);
          calloc.free(cPath);

          if (success) {
            _loadedLocales.add(locale);
            return true;
          }
        } catch (e) {
          // Asset load failed
        }
      }
    } catch (e) {
      // Load failed
    }

    return false;
  }

  static String t(String locale, String key, {Map<String, String>? params}) {
    if (!_initialized) return key;

    if (!_loadedLocales.contains(locale)) {
      loadLocale(locale);
    }

    final cLocale = locale.toNativeUtf8();
    final cKey = key.toNativeUtf8();
    
    ffi.Pointer<Utf8> cParams = ffi.Pointer.fromAddress(0);
    if (params != null && params.isNotEmpty) {
      cParams = json.encode(params).toNativeUtf8();
    }

    final resPtr = _translateWithParams(cLocale, cKey, cParams);
    
    calloc.free(cLocale);
    calloc.free(cKey);
    if (cParams.address != 0) {
      calloc.free(cParams);
    }

    if (resPtr.address == 0) return key;

    final result = resPtr.toDartString();
    _freeString(resPtr);
    return result;
  }

  static void clear() {
    if (!_initialized) return;
    _clear();
    _loadedLocales.clear();
  }

  // Helpers type-safe generados
{{HELPERS}}
}
