// Code generated by l10n4x-toolkit. DO NOT EDIT.
import 'dart:ffi' as ffi;
import 'dart:io';
import 'package:ffi/ffi.dart';
import 'package:flutter/services.dart' show rootBundle;

abstract final class L10nKeys {
{{KEY_DEFINITIONS}}
}

abstract final class L10nErrors {
  static const int ok = 0;
  static const int keyNotFound = 1;
  static const int localeNotLoaded = 2;
  static const int bufferTooSmall = 3;
  static const int invalidParams = 4;
  static const int internalError = 5;
  static const int invalidEncoding = 6;
  static const int ioError = 7;
  static const int signatureInvalid = 8;
  static const int verifyKeyNotSet = 9;
  static const int decryptKeyNotSet = 11;
  static const int bufferOverflow = 12;
}

final class L10n4cParam extends ffi.Struct {
  external ffi.Pointer<Utf8> key;
  external ffi.Pointer<Utf8> value;
}

typedef l10n4c_set_verify_key_func = ffi.Int32 Function(ffi.Pointer<ffi.Uint8> key, int key_len);
typedef L10n4cSetVerifyKey = int Function(ffi.Pointer<ffi.Uint8> key, int key_len);
{{DECRYPT_KEY_TYPEDEFS}}

typedef l10n4c_set_fallback_locale_func = ffi.Int32 Function(ffi.Pointer<Utf8> locale);
typedef L10n4cSetFallbackLocale = int Function(ffi.Pointer<Utf8> locale);

typedef l10n4c_load_lpk_locale_func = ffi.Int32 Function(ffi.Pointer<Utf8> locale, ffi.Pointer<Utf8> file_path);
typedef L10n4cLoadLpkLocale = int Function(ffi.Pointer<Utf8> locale, ffi.Pointer<Utf8> file_path);

typedef l10n4c_translate_alloc_func = ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> locale, ffi.Pointer<Utf8> key);
typedef L10n4cTranslateAlloc = ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> locale, ffi.Pointer<Utf8> key);

typedef l10n4c_translate_with_params_alloc_func = ffi.Pointer<Utf8> Function(
  ffi.Pointer<Utf8> locale,
  ffi.Pointer<Utf8> key,
  ffi.Pointer<L10n4cParam> params,
  int param_count,
);
typedef L10n4cTranslateWithParamsAlloc = ffi.Pointer<Utf8> Function(
  ffi.Pointer<Utf8> locale,
  ffi.Pointer<Utf8> key,
  ffi.Pointer<L10n4cParam> params,
  int param_count,
);

typedef l10n4c_free_string_func = ffi.Void Function(ffi.Pointer<Utf8> ptr);
typedef L10n4cFreeString = void Function(ffi.Pointer<Utf8> ptr);

typedef l10n4c_clear_func = ffi.Void Function();
typedef L10n4cClear = void Function();

class L10n {
  static late final ffi.DynamicLibrary _lib;
  static late final L10n4cSetVerifyKey _setVerifyKey;
{{DECRYPT_KEY_FIELDS}}  static late final L10n4cSetFallbackLocale _setFallbackLocale;
  static late final L10n4cLoadLpkLocale _loadLpkLocale;
  static late final L10n4cTranslateAlloc _translateAlloc;
  static late final L10n4cTranslateWithParamsAlloc _translateWithParamsAlloc;
  static late final L10n4cFreeString _freeString;
  static late final L10n4cClear _clear;

  static bool _initialized = false;
  static final Set<String> _loadedLocales = {};
  static String _fallback = '{{FALLBACK_LOCALE}}';
  static String _languagesDir = '{{OUTPUT_DIR}}';
  static final List<int> _verifyKeyBytes = <int>[ {{VERIFY_KEY_BYTES}} ];

  static void init({String? fallbackLocale, String? dir}) {
    if (_initialized) return;

    if (Platform.isAndroid) {
      _lib = ffi.DynamicLibrary.open('libl10n4c.so');
    } else if (Platform.isIOS || Platform.isMacOS) {
      _lib = ffi.DynamicLibrary.process();
    } else if (Platform.isLinux) {
      _lib = ffi.DynamicLibrary.open('libl10n4c.so');
    } else if (Platform.isWindows) {
      _lib = ffi.DynamicLibrary.open('l10n4c.dll');
    } else {
      throw UnsupportedError('Unsupported platform');
    }

    _setVerifyKey = _lib.lookup<ffi.NativeFunction<l10n4c_set_verify_key_func>>('l10n4c_set_verify_key').asFunction();
{{DECRYPT_KEY_LOOKUP}}    _setFallbackLocale = _lib.lookup<ffi.NativeFunction<l10n4c_set_fallback_locale_func>>('l10n4c_set_fallback_locale').asFunction();
    _loadLpkLocale = _lib.lookup<ffi.NativeFunction<l10n4c_load_lpk_locale_func>>('l10n4c_load_lpk_locale').asFunction();
    _translateAlloc = _lib.lookup<ffi.NativeFunction<l10n4c_translate_alloc_func>>('l10n4c_translate_alloc').asFunction();
    _translateWithParamsAlloc = _lib.lookup<ffi.NativeFunction<l10n4c_translate_with_params_alloc_func>>('l10n4c_translate_with_params_alloc').asFunction();
    _freeString = _lib.lookup<ffi.NativeFunction<l10n4c_free_string_func>>('l10n4c_free_string').asFunction();
    _clear = _lib.lookup<ffi.NativeFunction<l10n4c_clear_func>>('l10n4c_clear').asFunction();

    _fallback = fallbackLocale ?? _fallback;
    _languagesDir = dir ?? _languagesDir;

    final keyPtr = calloc<ffi.Uint8>(32);
    for (var i = 0; i < 32; i++) {
      keyPtr[i] = _verifyKeyBytes[i];
    }
    if (_setVerifyKey(keyPtr, 32) != 0) {
      calloc.free(keyPtr);
      throw StateError('l10n4c: invalid verify public key');
    }
    calloc.free(keyPtr);
{{DECRYPT_KEY_INIT}}
    final cFallback = _fallback.toNativeUtf8();
    _setFallbackLocale(cFallback);
    calloc.free(cFallback);

    _initialized = true;
    loadLocale(_fallback);
  }

  static Future<bool> loadLocale(String locale) async {
    if (!_initialized) return false;
    if (_loadedLocales.contains(locale)) return true;

    try {
      final lpkPath = '$_languagesDir/$locale.lpk';
      final file = File(lpkPath);
      if (await file.exists()) {
        final cLocale = locale.toNativeUtf8();
        final cPath = lpkPath.toNativeUtf8();
        final success = _loadLpkLocale(cLocale, cPath) == 0;
        calloc.free(cLocale);
        calloc.free(cPath);
        if (success) {
          _loadedLocales.add(locale);
          return true;
        }
      } else {
        try {
          final byteData = await rootBundle.load('assets/locales/$locale.lpk');
          final tempDir = await Directory.systemTemp.createTemp();
          final tempFile = File('${tempDir.path}/$locale.lpk');
          await tempFile.writeAsBytes(byteData.buffer.asUint8List());

          final cLocale = locale.toNativeUtf8();
          final cPath = tempFile.path.toNativeUtf8();
          final success = _loadLpkLocale(cLocale, cPath) == 0;
          calloc.free(cLocale);
          calloc.free(cPath);

          if (success) {
            _loadedLocales.add(locale);
            return true;
          }
        } catch (_) {}
      }
    } catch (_) {}

    return false;
  }

  static String t(String locale, String key, {Map<String, String>? params}) {
    if (!_initialized) return key;

    if (!_loadedLocales.contains(locale)) {
      loadLocale(locale);
    }

    final cLocale = locale.toNativeUtf8();
    final cKey = key.toNativeUtf8();

    ffi.Pointer<Utf8> resPtr;
    final paramPtrs = <(Pointer<Utf8>, Pointer<Utf8>)>[];

    if (params != null && params.isNotEmpty) {
      final array = calloc<L10n4cParam>(params.length);
      var i = 0;
      for (final entry in params.entries) {
        final ck = entry.key.toNativeUtf8();
        final cv = entry.value.toNativeUtf8();
        paramPtrs.add((ck, cv));
        array[i] = L10n4cParam()..key = ck..value = cv;
        i++;
      }
      resPtr = _translateWithParamsAlloc(cLocale, cKey, array, params.length);
      calloc.free(array);
      for (final (ck, cv) in paramPtrs) {
        calloc.free(ck);
        calloc.free(cv);
      }
    } else {
      resPtr = _translateAlloc(cLocale, cKey);
    }

    calloc.free(cLocale);
    calloc.free(cKey);

    if (resPtr.address == 0) return key;

    final result = resPtr.toDartString();
    _freeString(resPtr);
    return result;
  }

  static void clear() {
    if (!_initialized) return;
    _clear();
    _loadedLocales.clear();
  }

{{HELPERS}}
}