// Code generated by l10n4x-toolkit. DO NOT EDIT.
package {{PACKAGE_NAME}}

/*
#cgo LDFLAGS: -L. -ll10n4c -ldl -lpthread
#include <stdlib.h>
#include <stdint.h>
#include "l10n4c.h"
*/
import "C"
import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"unsafe"
)

var (
	loadedLocales = make(map[string]bool)
	mu            sync.RWMutex
	initialized   sync.Once
	fallback      = "{{FALLBACK_LOCALE}}"
	languagesDir  = "{{OUTPUT_DIR}}"
	verifyKey     = [32]byte{ {{VERIFY_KEY_BYTES}} }
)

func Init(fallbackLocale string, dir string) {
	initialized.Do(func() {
		fallback = fallbackLocale
		languagesDir = dir

		if C.l10n4c_set_verify_key((*C.uchar)(&verifyKey[0]), C.size_t(32)) != C.L10N4C_OK {
			panic("l10n4c: invalid verify public key")
		}
{{DECRYPT_KEY_INIT}}
		cFallback := C.CString(fallback)
		defer C.free(unsafe.Pointer(cFallback))
		C.l10n4c_set_fallback_locale(cFallback)

		loadLocale(fallback)
	})
}

func loadLocale(locale string) bool {
	mu.Lock()
	defer mu.Unlock()

	if loadedLocales[locale] {
		return true
	}

	pakPath := filepath.Join(languagesDir, locale+".pak")
	if _, err := os.Stat(pakPath); os.IsNotExist(err) {
		currentDir := languagesDir
		for i := 0; i < 6; i++ {
			testPath := filepath.Join(currentDir, locale+".pak")
			if _, statErr := os.Stat(testPath); statErr == nil {
				pakPath = testPath
				break
			}
			currentDir = filepath.Join("..", currentDir)
		}
	}

	cLocale := C.CString(locale)
	defer C.free(unsafe.Pointer(cLocale))
	cPath := C.CString(pakPath)
	defer C.free(unsafe.Pointer(cPath))

	success := C.l10n4c_load_pak_locale(cLocale, cPath) == C.L10N4C_OK
	if success {
		loadedLocales[locale] = true
	}
	return success
}

func toCParams(params map[string]string) ([]C.L10n4cParam, []unsafe.Pointer) {
	if len(params) == 0 {
		return nil, nil
	}
	cParams := make([]C.L10n4cParam, 0, len(params))
	toFree := make([]unsafe.Pointer, 0, len(params)*2)
	for k, v := range params {
		ck := C.CString(k)
		cv := C.CString(v)
		toFree = append(toFree, unsafe.Pointer(ck), unsafe.Pointer(cv))
		cParams = append(cParams, C.L10n4cParam{key: ck, value: cv})
	}
	return cParams, toFree
}

func T(locale string, key Key, params ...map[string]string) string {
	Init(fallback, languagesDir)

	locale = strings.ToLower(strings.TrimSpace(locale))
	if locale == "" {
		locale = fallback
	}

	mu.RLock()
	loaded := loadedLocales[locale]
	mu.RUnlock()

	if !loaded {
		if !loadLocale(locale) {
			mu.RLock()
			fallbackLoaded := loadedLocales[fallback]
			mu.RUnlock()
			if !fallbackLoaded {
				loadLocale(fallback)
			}
		}
	}

	cLocale := C.CString(locale)
	defer C.free(unsafe.Pointer(cLocale))
	cKey := C.CString(string(key))
	defer C.free(unsafe.Pointer(cKey))

	var ptr *C.char
	if len(params) > 0 && params[0] != nil && len(params[0]) > 0 {
		cParams, toFree := toCParams(params[0])
		for _, p := range toFree {
			defer C.free(p)
		}
		ptr = C.l10n4c_translate_with_params_alloc(
			cLocale, cKey, &cParams[0], C.size_t(len(cParams)),
		)
	} else {
		ptr = C.l10n4c_translate_alloc(cLocale, cKey)
	}

	if ptr == nil {
		return string(key)
	}
	defer C.l10n4c_free_string(ptr)
	return C.GoString(ptr)
}

func Clear() {
	mu.Lock()
	defer mu.Unlock()
	C.l10n4c_clear()
	loadedLocales = make(map[string]bool)
}