// Code generated by l10n4x-toolkit. DO NOT EDIT.
import init, {
  l10n4x_set_encryption_key,
  l10n4x_set_fallback_locale,
  l10n4x_load_pak_bytes,
  l10n4x_translate,
  l10n4x_clear
} from "l10n4x-wasm";

export type LocaleKey =
{{KEY_DEFINITIONS}};

let initialized = false;
const loadedLocales = new Set<string>();
let fallback = "{{FALLBACK_LOCALE}}";
let keyEnvName = "{{KEY_ENV}}";
let outputDir = "{{OUTPUT_DIR}}";

export async function initializeI18n(options?: {
  wasmUrl?: string;
  encryptionKey?: string;
  fallbackLocale?: string;
  localesPath?: string;
}) {
  if (initialized) return;

  const wasmUrl = options?.wasmUrl;
  const encryptionKey = options?.encryptionKey || (typeof process !== "undefined" ? process.env[keyEnvName] : undefined);
  fallback = options?.fallbackLocale || fallback;
  outputDir = options?.localesPath || outputDir;

  await init(wasmUrl);

  if (encryptionKey) {
    const encoder = new TextEncoder();
    const keyBytes = encoder.encode(encryptionKey);
    if (keyBytes.length === 32) {
      l10n4x_set_encryption_key(keyBytes);
    } else {
      console.warn("l10n4x: Encryption key must be exactly 32 bytes.");
    }
  }

  l10n4x_set_fallback_locale(fallback);
  initialized = true;

  await loadLocale(fallback);
}

export async function loadLocale(locale: string): Promise<boolean> {
  if (loadedLocales.has(locale)) return true;

  try {
    let bytes: Uint8Array;
    if (typeof window !== "undefined" || typeof fetch !== "undefined") {
      const url = `${outputDir}/${locale}.pak`;
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
      const arrayBuffer = await res.arrayBuffer();
      bytes = new Uint8Array(arrayBuffer);
    } else {
      const fs = require("fs");
      const path = require("path");
      const filePath = path.resolve(outputDir, `${locale}.pak`);
      const buffer = fs.readFileSync(filePath);
      bytes = new Uint8Array(buffer);
    }

    const success = l10n4x_load_pak_bytes(bytes, locale);
    if (success) {
      loadedLocales.add(locale);
      return true;
    }
  } catch (err) {
    console.error(`l10n4x: Failed to load locale "${locale}":`, err);
  }
  return false;
}

export function t(locale: string, key: LocaleKey, params?: Record<string, string>): string {
  if (!initialized) {
    return key;
  }
  const paramsJson = params ? JSON.stringify(params) : "";
  return l10n4x_translate(locale, key, paramsJson);
}

export function useI18n(initialLocale: string) {
  const React = typeof window !== "undefined" ? (window as any).React : null;
  const [currentLocale, setCurrentLocale] = React ? React.useState(initialLocale) : [initialLocale, (l: string) => {}];
  const [isLoading, setIsLoading] = React ? React.useState(false) : [false, (b: boolean) => {}];

  const changeLocale = async (newLocale: string) => {
    setIsLoading(true);
    await loadLocale(newLocale);
    setCurrentLocale(newLocale);
    setIsLoading(false);
  };

  return {
    t: (key: LocaleKey, params?: Record<string, string>) => t(currentLocale, key, params),
    locale: currentLocale,
    setLocale: changeLocale,
    isLoading
  };
}
