// Code generated by l10n4x-toolkit. DO NOT EDIT.
import init, {
  l10n4x_set_verify_key,
{{DECRYPT_KEY_IMPORT}}  l10n4x_set_fallback_locale,
  l10n4x_load_pak_bytes,
  l10n4x_translate,
  l10n4x_translate_with_params,
  l10n4x_clear
} from "l10n4x-wasm";

// ---------------------------------------------------------------------------
// Generated constants
// ---------------------------------------------------------------------------

export type LocaleKey = number;

{{KEY_DEFINITIONS}}

export const L10nErrors = {
  OK: 0,
  KEY_NOT_FOUND: 1,
  LOCALE_NOT_LOADED: 2,
  BUFFER_TOO_SMALL: 3,
  INVALID_PARAMS: 4,
  INTERNAL_ERROR: 5,
  INVALID_ENCODING: 6,
  IO_ERROR: 7,
  SIGNATURE_INVALID: 8,
  VERIFY_KEY_NOT_SET: 9,
  DECRYPT_KEY_NOT_SET: 11,
  BUFFER_OVERFLOW: 12,
} as const;

const _FALLBACK_LOCALE = "{{FALLBACK_LOCALE}}";
const _OUTPUT_DIR = "{{OUTPUT_DIR}}";
const _VERIFY_PUBLIC_KEY_HEX = "{{VERIFY_PUBLIC_KEY}}";
{{ENCRYPT_BLOCK}}
// ---------------------------------------------------------------------------
// Loader abstraction — swap for SSR / custom transports
// ---------------------------------------------------------------------------

/**
 * A PakLoader fetches or reads a locale's `.pak` file and returns its bytes.
 *
 * Two built-in implementations are provided:
 *   - `fetchPakLoader`  — browser / Fetch API
 *   - `fsPakLoader`     — Node.js / SSR (fs/promises)
 *
 * You can inject your own via `initializeI18n({ loader: myLoader })`.
 */
export type PakLoader = (locale: string, baseDir: string) => Promise<Uint8Array>;

/**
 * Browser loader — uses the Fetch API.
 * `baseDir` is treated as a URL prefix, e.g. "/locales".
 */
export const fetchPakLoader: PakLoader = async (locale, baseDir) => {
  const url = `${baseDir}/${locale}.pak`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`l10n4x: HTTP ${res.status} for ${url}`);
  return new Uint8Array(await res.arrayBuffer());
};

/**
 * Node.js / SSR loader — uses `fs/promises`.
 * `baseDir` is treated as a filesystem path.
 */
export const fsPakLoader: PakLoader = async (locale, baseDir) => {
  const fs = await import("fs/promises");
  const path = await import("path");
  const filePath = path.join(baseDir, `${locale}.pak`);
  try {
    const buf = await fs.readFile(filePath);
    return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`l10n4x: failed to read '${filePath}': ${msg}`);
  }
};

/**
 * Auto-detect: uses `fetchPakLoader` when `fetch` is available (browser /
 * edge runtimes), otherwise falls back to `fsPakLoader` (Node.js).
 */
export const autoPakLoader: PakLoader = (locale, baseDir) =>
  typeof fetch !== "undefined"
    ? fetchPakLoader(locale, baseDir)
    : fsPakLoader(locale, baseDir);

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

let _initialized = false;
let _fallback = _FALLBACK_LOCALE;
let _outputDir = _OUTPUT_DIR;
let _loader: PakLoader = autoPakLoader;
const _loadedLocales = new Set<string>();

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export async function initializeI18n(options?: {
  /**
   * Custom pak loader. Defaults to `autoPakLoader` (Fetch in browser, fs on
   * Node). Pass `fetchPakLoader` or `fsPakLoader` explicitly to force one
   * environment, or supply your own implementation.
   *
   * @example SSR with explicit fs loader:
   *   await initializeI18n({ loader: fsPakLoader });
   *
   * @example Browser with custom CDN:
   *   await initializeI18n({
   *     loader: (locale, _) => fetchPakLoader(locale, "https://cdn.example.com/locales"),
   *   });
   */
  loader?: PakLoader;
  /** WASM binary URL or pre-fetched module. */
  wasmUrl?: string;
  /** Override the fallback locale from the generated config. */
  fallbackLocale?: string;
  /** Override the locales base path / URL. */
  localesPath?: string;
  decryptKey?: Uint8Array;
}) {
  if (_initialized) return;

  _fallback = options?.fallbackLocale ?? _fallback;
  _outputDir = options?.localesPath ?? _outputDir;
  _loader = options?.loader ?? _loader;

  await init(options?.wasmUrl);
  l10n4x_set_verify_key(hexToBytes(_VERIFY_PUBLIC_KEY_HEX));
{{DECRYPT_KEY_INIT}}  l10n4x_set_fallback_locale(_fallback);
  _initialized = true;
  await loadLocale(_fallback);
}

const CACHE_PREFIX = "l10n4x_pak_";

function cacheKey(locale: string): string {
  return `${CACHE_PREFIX}${_outputDir}:${locale}`;
}

async function loadLocaleWithCache(locale: string): Promise<boolean> {
  if (_loadedLocales.has(locale)) return true;

  // Try browser cache (localStorage)
  if (typeof localStorage !== "undefined") {
    const cached = localStorage.getItem(cacheKey(locale));
    if (cached) {
      try {
        const parsed = JSON.parse(cached);
        const bytes = new Uint8Array(parsed);
        l10n4x_load_pak_bytes(bytes, locale);
        _loadedLocales.add(locale);
        return true;
      } catch {
        localStorage.removeItem(cacheKey(locale));
      }
    }
  }

  // Network / disk load
  try {
    const bytes = await _loader(locale, _outputDir);
    l10n4x_load_pak_bytes(bytes, locale);
    _loadedLocales.add(locale);

    // Cache for next time
    if (typeof localStorage !== "undefined") {
      try {
        localStorage.setItem(cacheKey(locale), JSON.stringify(Array.from(bytes)));
      } catch {
        // localStorage full — silently ignore
      }
    }
    return true;
  } catch (e) {
    console.warn(`l10n4x: failed to load locale '${locale}':`, e);
    throw e;
  }
}

export async function loadLocale(locale: string): Promise<boolean> {
  return loadLocaleWithCache(locale);
}

export function t(
  locale: string,
  key: LocaleKey,
  params?: Record<string, string>
): string {
  if (!_initialized) throw new Error("l10n4x: call initializeI18n() first");

  const normalized = (locale || _fallback).toLowerCase().trim();
  if (!_loadedLocales.has(normalized)) void loadLocale(normalized);

  if (!params || Object.keys(params).length === 0) {
    return l10n4x_translate(normalized, key);
  }
  const keys = Object.keys(params);
  const values = keys.map((k) => params[k]!);
  return l10n4x_translate_with_params(normalized, key, keys, values);
}

export function clearI18n(): void {
  l10n4x_clear();
  _loadedLocales.clear();
  _initialized = false;
}

// ── Dev server hot-reload integration ─────────────────────────────────────────
/**
 * Connects to the l10n4x dev server SSE endpoint and reloads paks automatically
 * when files change. Call during development only.
 * @param baseUrl  Dev server base URL, e.g. "http://localhost:3456"
 * @param locales  List of locale codes to reload on change
 */
export function connectDevServer(baseUrl: string, locales: string[]): () => void {
  const url = `${baseUrl}/events`;
  const es = new EventSource(url);
  es.onmessage = async () => {
    await Promise.all(locales.map((locale) => loadLocale(locale)));
  };
  es.onerror = () => {
    console.warn("[l10n4x] Dev server connection lost. Retrying...");
  };
  return () => es.close();
}

{{REACT_BLOCK}}