// Code generated by l10n4x-toolkit. DO NOT EDIT.
// Runtime: @l10n4x/runtime — framework: @l10n4x/react | @l10n4x/vue | @l10n4x/svelte | @l10n4x/angular

/** u64 key hash emitted by l10n4x build. */
export type LocaleKey = number;

export const Keys = {
{{KEY_ENTRIES}}
} as const;

export type KeyName = keyof typeof Keys;

{{PARAM_TYPES}}