use crate::targets::GenerateContext;
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

pub fn generate(
    out_dir: &Path,
    key_pairs: &[(u64, String)],
    _options: &Value,
    ctx: &GenerateContext<'_>,
    _params_map: &HashMap<String, Vec<String>>,
) -> Result<(), anyhow::Error> {
    let mut key_definitions = String::new();
    for (hash, name) in key_pairs {
        let pascal_name = crate::generator::to_pascal_case(name);
        key_definitions.push_str(&format!("export const {} = 0x{:016x} as const;\n", pascal_name, hash));
    }

    let service = format!(
        r#"// Code generated by l10n4x-toolkit. DO NOT EDIT.
import {{ Injectable, inject }} from '@angular/core';
import {{ BehaviorSubject, Observable }} from 'rxjs';
import {{
  t as coreT,
  loadLocale,
  initializeI18n,
}} from './generated';

export type LocaleKey = number;

{keys}
@Injectable({{ providedIn: 'root' }})
export class I18nService {{
  private readonly _locale = new BehaviorSubject<string>('{fallback}');
  readonly locale$: Observable<string> = this._locale.asObservable();
  private _initialized = false;

  async init(locale?: string): Promise<void> {{
    if (this._initialized) return;
    await initializeI18n();
    this._initialized = true;
    const loc = locale ?? '{fallback}';
    await loadLocale(loc);
    this._locale.next(loc);
  }}

  async setLocale(locale: string): Promise<void> {{
    if (!this._initialized) {{
      await this.init(locale);
      return;
    }}
    await loadLocale(locale);
    this._locale.next(locale);
  }}

  translate(key: LocaleKey, locale?: string): string {{
    return coreT(locale ?? this._locale.getValue(), key);
  }}

  translateWithParams(key: LocaleKey, params: Record<string, string | number>, locale?: string): string {{
    return coreT(locale ?? this._locale.getValue(), key, params);
  }}

  onLocaleChanged(): Observable<string> {{
    return this.locale$;
  }}
}}
"#,
        keys = key_definitions,
        fallback = ctx.fallback,
    );

    let pipe = r#"// Code generated by l10n4x-toolkit. DO NOT EDIT.
import { Pipe, PipeTransform, inject } from '@angular/core';
import { I18nService } from './i18n.service';

@Pipe({
  name: 'i18n',
  pure: false,
})
export class I18nPipe implements PipeTransform {
  private readonly service = inject(I18nService);

  transform(key: string, ...args: any[]): string {
    if (args.length === 0) {
      return this.service.translate(key as any);
    }
    if (args.length === 1 && typeof args[0] === 'object') {
      return this.service.translateWithParams(key as any, args[0]);
    }
    if (args.length === 1) {
      return this.service.translate(key as any, args[0] as string);
    }
    if (args.length >= 2) {
      return this.service.translateWithParams(key as any, args[1] as any, args[0] as string);
    }
    return this.service.translate(key as any);
  }
}
"#.to_string();

    let module = r#"// Code generated by l10n4x-toolkit. DO NOT EDIT.
import { NgModule } from '@angular/core';
import { I18nService } from './i18n.service';
import { I18nPipe } from './i18n.pipe';

@NgModule({
  providers: [I18nService],
  declarations: [I18nPipe],
  exports: [I18nPipe],
})
export class I18nModule {}
"#.to_string();

    let index = r#"// Code generated by l10n4x-toolkit. DO NOT EDIT.
export { I18nService } from './i18n.service';
export { I18nPipe } from './i18n.pipe';
export { I18nModule } from './i18n.module';
export type { LocaleKey } from './i18n.service';
"#.to_string();

    fs::write(out_dir.join("i18n.service.ts"), service)?;
    fs::write(out_dir.join("i18n.pipe.ts"), pipe)?;
    fs::write(out_dir.join("i18n.module.ts"), module)?;
    fs::write(out_dir.join("index.ts"), index)?;
    println!("Generated Angular bindings at '{}'", out_dir.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::targets::GenerateContext;
    use std::collections::HashMap;

    fn test_ctx() -> GenerateContext<'static> {
        GenerateContext {
            fallback: "en",
            output_dir: "",
            source_dir: "",
            verify_key_bytes: "000000000000000000000000000000000000000000000000000000000000000000",
            verify_public_key_hex: "",
            encrypt: false,
            encrypt_key_env: "",
        }
    }

    #[test]
    fn generates_service_with_keys() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![(0xabcdef0123456789, "welcome.title".to_string())];
        let params = HashMap::new();
        generate(dir.path(), &key_pairs, &Value::Null, &test_ctx(), &params).unwrap();
        let content = std::fs::read_to_string(dir.path().join("i18n.service.ts")).unwrap();
        assert!(content.contains("I18nService"));
        assert!(content.contains("export const WelcomeTitle = 0xabcdef0123456789 as const;"));
    }

    #[test]
    fn generates_all_angular_artifacts() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![(0xabcdef0123456789, "k".to_string())];
        let params = HashMap::new();
        generate(dir.path(), &key_pairs, &Value::Null, &test_ctx(), &params).unwrap();
        assert!(dir.path().join("i18n.service.ts").exists());
        assert!(dir.path().join("i18n.pipe.ts").exists());
        assert!(dir.path().join("i18n.module.ts").exists());
        assert!(dir.path().join("index.ts").exists());
    }
}
