use serde_json::Value;
use std::fs;
use std::path::Path;

pub fn generate(
    out_dir: &Path,
    key_pairs: &[(u64, String)],
    _options: &Value,
    to_upper_snake_case: fn(&str) -> String,
) -> Result<(), anyhow::Error> {
    let mut definitions = String::new();
    let mut to_string_cases = String::new();
    let mut from_string_cases = String::new();

    for (hash, name) in key_pairs {
        let def_name = to_upper_snake_case(name);
        definitions.push_str(&format!("#define L10N4X_{} 0x{:016x}ULL\n", def_name, hash));
        to_string_cases.push_str(&format!(
            "        case L10N4X_{}: return \"{}\";\n",
            def_name, name
        ));
        from_string_cases.push_str(&format!(
            "    if (strcmp(str, \"{}\") == 0) return L10N4X_{};\n",
            name, def_name
        ));
    }

    // Generate .h
    let header_content = format!(
        "// Code generated by l10n4x-toolkit. DO NOT EDIT.\n#ifndef L10N4X_KEYS_H\n#define L10N4X_KEYS_H\n\n#include <stdint.h>\n\n{}\nconst char* l10n4x_key_to_string(uint64_t key);\nuint64_t l10n4x_key_from_string(const char* str);\n\n#endif\n",
        definitions
    );
    let header_path = out_dir.join("l10n4x_keys.h");
    fs::write(&header_path, header_content)?;

    // Generate .c
    let source_content = format!(
        "// Code generated by l10n4x-toolkit. DO NOT EDIT.\n#include \"l10n4x_keys.h\"\n#include <string.h>\n\nconst char* l10n4x_key_to_string(uint64_t key) {{\n    switch(key) {{\n{}        default: return \"\";\n    }}\n}}\n\nuint64_t l10n4x_key_from_string(const char* str) {{\n{}    return 0;\n}}\n",
        to_string_cases, from_string_cases
    );
    let source_path = out_dir.join("l10n4x_keys.c");
    fs::write(&source_path, source_content)?;
    println!("Generated C bindings at '{}'", out_dir.display());

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_header_and_source() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![(0xabcdef0123456789, "common.welcome".to_string())];
        generate(dir.path(), &key_pairs, &Value::Null, |s| s.to_uppercase().replace('.', "_")).unwrap();
        assert!(dir.path().join("l10n4x_keys.h").exists());
        assert!(dir.path().join("l10n4x_keys.c").exists());
        let header = std::fs::read_to_string(dir.path().join("l10n4x_keys.h")).unwrap();
        assert!(header.contains("L10N4X_COMMON_WELCOME"));
        assert!(header.contains("uint64_t"));
    }

    #[test]
    fn header_has_include_guard() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![(0xabcdef0123456789, "k".to_string())];
        generate(dir.path(), &key_pairs, &Value::Null, |s| s.to_string()).unwrap();
        let header = std::fs::read_to_string(dir.path().join("l10n4x_keys.h")).unwrap();
        assert!(header.starts_with("// Code generated"));
        assert!(header.contains("#ifndef L10N4X_KEYS_H"));
    }
}
