use std::fs;
use std::path::Path;
use serde_json::Value;

pub fn generate(
    out_dir: &Path,
    sorted_keys: &[String],
    _options: &Value,
    to_upper_snake_case: fn(&str) -> String,
) -> Result<(), anyhow::Error> {
    let mut enum_definitions = String::new();
    let mut to_string_cases = String::new();
    let mut from_string_cases = String::new();

    for k in sorted_keys {
        let name = to_upper_snake_case(k);
        enum_definitions.push_str(&format!("    L10N4X_{},\n", name));
        to_string_cases.push_str(&format!("        case L10N4X_{}: return \"{}\";\n", name, k));
        from_string_cases.push_str(&format!("    if (strcmp(str, \"{}\") == 0) return L10N4X_{};\n", k, name));
    }

    // Generate .h
    let header_content = format!(
        "// Code generated by l10n4x-toolkit. DO NOT EDIT.\n#ifndef L10N4X_KEYS_H\n#define L10N4X_KEYS_H\n\ntypedef enum {{\n{}    L10N4X_KEY_COUNT\n}} l10n4x_key_t;\n\nconst char* l10n4x_key_to_string(l10n4x_key_t key);\nl10n4x_key_t l10n4x_key_from_string(const char* str);\n\n#endif\n",
        enum_definitions
    );
    let header_path = out_dir.join("l10n4x_keys.h");
    fs::write(&header_path, header_content)?;

    // Generate .c
    let source_content = format!(
        "// Code generated by l10n4x-toolkit. DO NOT EDIT.\n#include \"l10n4x_keys.h\"\n#include <string.h>\n\nconst char* l10n4x_key_to_string(l10n4x_key_t key) {{\n    switch(key) {{\n{}        default: return \"\";\n    }}\n}}\n\nl10n4x_key_t l10n4x_key_from_string(const char* str) {{\n{}    return L10N4X_KEY_COUNT;\n}}\n",
        to_string_cases, from_string_cases
    );
    let source_path = out_dir.join("l10n4x_keys.c");
    fs::write(&source_path, source_content)?;
    println!("Generated C bindings at '{}'", out_dir.display());

    Ok(())
}
