use crate::targets::GenerateContext;
use serde_json::Value;
use std::fs;
use std::path::Path;

const GO_TEMPLATE: &str = include_str!("../templates/go_i18n.go");

fn go_decrypt_key_init(ctx: &GenerateContext<'_>) -> String {
    if !ctx.encrypt {
        return String::new();
    }
    format!(
        r#"
		if raw := os.Getenv("{env}"); len(raw) == 32 {{
			var encKey [32]byte
			copy(encKey[:], raw)
			if C.l10n4c_set_decrypt_key((*C.uchar)(&encKey[0]), C.size_t(32)) != C.L10N4C_OK {{
				panic("l10n4c: invalid decrypt key")
			}}
		}} else {{
			panic("l10n4c: encryptKeyEnv not set or wrong length")
		}}
"#,
        env = ctx.encrypt_key_env
    )
}

pub fn generate(
    out_dir: &Path,
    key_pairs: &[(u64, String)],
    options: &Value,
    ctx: &GenerateContext<'_>,
    to_pascal_case: fn(&str) -> String,
) -> Result<(), anyhow::Error> {
    let package_name = options
        .get("package")
        .and_then(|v| v.as_str())
        .unwrap_or("i18n");

    let mut content = format!(
        "// Code generated by l10n4x-toolkit. DO NOT EDIT.\npackage {}\n\ntype Key uint64\n\nconst (\n",
        package_name
    );
    for (hash, name) in key_pairs {
        let const_name = to_pascal_case(name);
        content.push_str(&format!("    {} = 0x{:016x},\n", const_name, hash));
    }
    content.push_str(")\n");

    let keys_file_path = out_dir.join("keys.go");
    fs::write(&keys_file_path, content)?;
    println!("Generated Go keys at '{}'", keys_file_path.display());

    let i18n_content = GO_TEMPLATE
        .replace("{{PACKAGE_NAME}}", package_name)
        .replace("{{FALLBACK_LOCALE}}", ctx.fallback)
        .replace("{{OUTPUT_DIR}}", ctx.output_dir)
        .replace("{{VERIFY_KEY_BYTES}}", ctx.verify_key_bytes)
        .replace("{{DECRYPT_KEY_INIT}}", &go_decrypt_key_init(ctx));

    let header_src = Path::new(env!("CARGO_MANIFEST_DIR")).join("../ffi/l10n4c.h");
    if header_src.exists() {
        fs::copy(&header_src, out_dir.join("l10n4c.h"))?;
    }

    let i18n_file_path = out_dir.join("i18n.go");
    fs::write(&i18n_file_path, i18n_content)?;
    println!(
        "Generated Go FFI integration at '{}'",
        i18n_file_path.display()
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generator::to_pascal_case;
    use crate::targets::GenerateContext;

    fn test_ctx() -> GenerateContext<'static> {
        GenerateContext {
            fallback: "en",
            output_dir: "",
            source_dir: "",
            verify_key_bytes: "000000000000000000000000000000000000000000000000000000000000000000",
            verify_public_key_hex: "",
            encrypt: false,
            encrypt_key_env: "",
        }
    }

    #[test]
    fn generates_key_constants() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![
            (0xabcdef0123456789, "common.welcome".to_string()),
            (0x123456789abcdef0, "user.name".to_string()),
        ];
        generate(
            dir.path(),
            &key_pairs,
            &serde_json::Value::Null,
            &test_ctx(),
            to_pascal_case,
        )
        .unwrap();
        let content = std::fs::read_to_string(dir.path().join("keys.go")).unwrap();
        assert!(content.contains("CommonWelcome"));
        assert!(content.contains("UserName"));
    }

    #[test]
    fn copies_l10n4c_header() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![(0xabcdef0123456789, "k".to_string())];
        generate(
            dir.path(),
            &key_pairs,
            &serde_json::Value::Null,
            &test_ctx(),
            to_pascal_case,
        )
        .unwrap();
        assert!(dir.path().join("l10n4c.h").exists());
    }
}
