use std::fs;
use std::path::Path;
use serde_json::Value;

const GO_TEMPLATE: &str = include_str!("../templates/go_i18n.go");

pub fn generate(
    out_dir: &Path,
    sorted_keys: &[String],
    options: &Value,
    fallback: &str,
    output_dir: &str,
    key_env: &str,
    to_pascal_case: fn(&str) -> String,
) -> Result<(), anyhow::Error> {
    let package_name = options.get("package")
        .and_then(|v| v.as_str())
        .unwrap_or("i18n");

    // 1. Generate keys.go
    let mut content = format!(
        "// Code generated by l10n4x-toolkit. DO NOT EDIT.\npackage {}\n\ntype Key string\n\nconst (\n",
        package_name
    );
    for k in sorted_keys {
        let const_name = to_pascal_case(k);
        content.push_str(&format!("    {} Key = \"{}\"\n", const_name, k));
    }
    content.push_str(")\n");

    let keys_file_path = out_dir.join("keys.go");
    fs::write(&keys_file_path, content)?;
    println!("Generated Go keys at '{}'", keys_file_path.display());

    // 2. Generate i18n.go using template
    let i18n_content = GO_TEMPLATE
        .replace("{{PACKAGE_NAME}}", package_name)
        .replace("{{FALLBACK_LOCALE}}", fallback)
        .replace("{{OUTPUT_DIR}}", output_dir)
        .replace("{{KEY_ENV}}", key_env);

    let i18n_file_path = out_dir.join("i18n.go");
    fs::write(&i18n_file_path, i18n_content)?;
    println!("Generated Go FFI integration at '{}'", i18n_file_path.display());

    Ok(())
}
