use serde_json::Value;
use std::fs;
use std::path::Path;

pub fn generate(
    out_dir: &Path,
    sorted_keys: &[String],
    _options: &Value,
    to_upper_snake_case: fn(&str) -> String,
) -> Result<(), anyhow::Error> {
    let mut python_definitions = String::new();
    for k in sorted_keys {
        let name = to_upper_snake_case(k);
        python_definitions.push_str(&format!("    {} = \"{}\"\n", name, k));
    }

    let content = format!(
        "# Code generated by l10n4x-toolkit. DO NOT EDIT.\nfrom enum import Enum\n\nclass L10nErrors:\n    OK = 0\n    KEY_NOT_FOUND = 1\n    LOCALE_NOT_LOADED = 2\n    BUFFER_TOO_SMALL = 3\n    INVALID_PARAMS = 4\n    INTERNAL_ERROR = 5\n    INVALID_ENCODING = 6\n    IO_ERROR = 7\n    SIGNATURE_INVALID = 8\n    VERIFY_KEY_NOT_SET = 9\n    DECRYPT_KEY_NOT_SET = 11\n    BUFFER_OVERFLOW = 12\n\nclass LocaleKey(str, Enum):\n{}\ndef translate(key: LocaleKey, **kwargs) -> str:\n    return str(key)\n",
        python_definitions
    );

    let file_path = out_dir.join("keys.py");
    fs::write(&file_path, content)?;
    println!("Generated Python bindings at '{}'", file_path.display());

    Ok(())
}
