use serde_json::Value;
use std::fs;
use std::path::Path;

pub fn generate(
    out_dir: &Path,
    key_pairs: &[(u64, String)],
    _options: &Value,
    to_upper_snake_case: fn(&str) -> String,
) -> Result<(), anyhow::Error> {
    let mut key_definitions = String::new();
    for (hash, name) in key_pairs {
        let def_name = to_upper_snake_case(name);
        key_definitions.push_str(&format!("    {} = 0x{:016x}\n", def_name, hash));
    }

    let content = format!(
        r#"# Code generated by l10n4x-toolkit. DO NOT EDIT.
# Requires: libl10n4c (.so / .dylib / .dll) on the library search path.
import ctypes
import os
import platform
from enum import Enum
from pathlib import Path
from typing import Optional

# ── Error codes (mirrors l10n4c.h) ────────────────────────────────────────────

class L10nErrors:
    OK = 0
    KEY_NOT_FOUND = 1
    LOCALE_NOT_LOADED = 2
    BUFFER_TOO_SMALL = 3
    INVALID_PARAMS = 4
    INTERNAL_ERROR = 5
    INVALID_ENCODING = 6
    IO_ERROR = 7
    SIGNATURE_INVALID = 8
    VERIFY_KEY_NOT_SET = 9
    DECRYPT_KEY_NOT_SET = 11
    BUFFER_OVERFLOW = 12

# ── Library loading ────────────────────────────────────────────────────────────

def _find_library() -> ctypes.CDLL:
    system = platform.system()
    if system == "Windows":
        names = ["l10n4c.dll"]
    elif system == "Darwin":
        names = ["libl10n4c.dylib", "libl10n4c.so"]
    else:
        names = ["libl10n4c.so", "libl10n4c.so.0"]

    search = [
        Path(__file__).parent,
        Path(__file__).parent.parent,
        Path(os.environ.get("L10N4X_LIB_DIR", "")),
        Path("/usr/local/lib"),
        Path("/usr/lib"),
    ]
    for base in search:
        for name in names:
            candidate = base / name
            if candidate.exists():
                return ctypes.CDLL(str(candidate))

    raise FileNotFoundError(
        f"l10n4c library not found. Set L10N4X_LIB_DIR or place the library next to {{__file__}}.\n"
        f"Searched: {{[str(p) for p in search]}}"
    )

_lib: Optional[ctypes.CDLL] = None

def _get_lib() -> ctypes.CDLL:
    global _lib
    if _lib is None:
        _lib = _find_library()
        _setup_signatures(_lib)
    return _lib

# ── C struct ──────────────────────────────────────────────────────────────────

class L10n4cParam(ctypes.Structure):
    _fields_ = [
        ("key",   ctypes.c_char_p),
        ("value", ctypes.c_char_p),
    ]

# ── Signature setup ───────────────────────────────────────────────────────────

def _setup_signatures(lib: ctypes.CDLL) -> None:
    lib.l10n4c_set_verify_key.argtypes    = [ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t]
    lib.l10n4c_set_verify_key.restype     = ctypes.c_bool
    lib.l10n4c_set_fallback_locale.argtypes = [ctypes.c_char_p]
    lib.l10n4c_set_fallback_locale.restype  = None
    lib.l10n4c_load_pak_locale.argtypes   = [ctypes.c_char_p, ctypes.c_char_p]
    lib.l10n4c_load_pak_locale.restype    = ctypes.c_int32
    lib.l10n4c_load_pak_directory.argtypes = [ctypes.c_char_p]
    lib.l10n4c_load_pak_directory.restype  = ctypes.c_bool
    lib.l10n4c_translate_with_params_alloc.argtypes = [
        ctypes.c_char_p, ctypes.c_char_p,
        ctypes.POINTER(L10n4cParam), ctypes.c_size_t,
    ]
    lib.l10n4c_translate_with_params_alloc.restype = ctypes.c_char_p
    lib.l10n4c_translate_alloc.argtypes   = [ctypes.c_char_p, ctypes.c_char_p]
    lib.l10n4c_translate_alloc.restype    = ctypes.c_char_p
    lib.l10n4c_free_string.argtypes       = [ctypes.c_char_p]
    lib.l10n4c_free_string.restype        = None
    lib.l10n4c_clear.argtypes             = []
    lib.l10n4c_clear.restype              = None

# ── Public API ────────────────────────────────────────────────────────────────

def set_verify_key(key_hex: str) -> bool:
    if len(key_hex) != 64:
        raise ValueError("verify key must be 64 hex characters (32 bytes)")
    raw = bytes.fromhex(key_hex)
    buf = (ctypes.c_uint8 * 32)(*raw)
    return bool(_get_lib().l10n4c_set_verify_key(buf, 32))

def set_fallback_locale(locale: str) -> None:
    _get_lib().l10n4c_set_fallback_locale(locale.encode("utf-8"))

def load_pak_locale(locale: str, path: str) -> int:
    return int(_get_lib().l10n4c_load_pak_locale(
        locale.encode("utf-8"), path.encode("utf-8")
    ))

def load_pak_directory(directory: str) -> bool:
    return bool(_get_lib().l10n4c_load_pak_directory(directory.encode("utf-8")))

def translate(key: "LocaleKey", locale: str = "en", **kwargs: str) -> str:
    lib = _get_lib()
    locale_b = locale.encode("utf-8")
    key_b    = str(key.value).encode("utf-8")

    if kwargs:
        params = [L10n4cParam(k.encode("utf-8"), str(v).encode("utf-8")) for k, v in kwargs.items()]
        arr    = (L10n4cParam * len(params))(*params)
        ptr    = lib.l10n4c_translate_with_params_alloc(locale_b, key_b, arr, len(params))
    else:
        ptr = lib.l10n4c_translate_alloc(locale_b, key_b)

    if not ptr:
        return str(key.value)
    result = ctypes.string_at(ptr).decode("utf-8")
    lib.l10n4c_free_string(ptr)
    return result

def clear() -> None:
    _get_lib().l10n4c_clear()

# ── Generated keys ────────────────────────────────────────────────────────────

class LocaleKey(int, Enum):
{key_definitions}
"#,
        key_definitions = key_definitions
    );

    let file_path = out_dir.join("keys.py");
    fs::write(&file_path, content)?;
    println!("Generated Python bindings at '{}'", file_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn run_generate(keys: &[&str]) -> String {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = keys.iter().enumerate().map(|(i, s)| (0xabcdef0123456789 + i as u64, s.to_string())).collect();
        generate(dir.path(), &key_pairs, &serde_json::Value::Null, |s| {
            s.to_uppercase().replace('.', "_")
        })
        .unwrap();
        std::fs::read_to_string(dir.path().join("keys.py")).unwrap()
    }

    #[test]
    fn generated_code_imports_ctypes() {
        let code = run_generate(&["welcome", "user.name"]);
        assert!(code.contains("import ctypes"));
    }

    #[test]
    fn translate_calls_ffi_not_stub() {
        let code = run_generate(&["greeting"]);
        assert!(!code.contains("return str(key)"));
        assert!(code.contains("_lib"));
    }

    #[test]
    fn contains_load_pak_locale() {
        let code = run_generate(&["k"]);
        assert!(code.contains("l10n4c_load_pak_locale"));
    }
}
