use crate::targets::GenerateContext;
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

pub fn generate(
    out_dir: &Path,
    sorted_keys: &[String],
    _options: &Value,
    ctx: &GenerateContext<'_>,
    _params_map: &HashMap<String, Vec<String>>,
) -> Result<(), anyhow::Error> {
    let mut key_definitions = String::new();
    for k in sorted_keys {
        key_definitions.push_str(&format!("  | \"{}\"\n", k));
    }
    if key_definitions.is_empty() {
        key_definitions = "  | string".to_string();
    } else {
        key_definitions = key_definitions.trim_end().to_string();
    }

    let content = format!(
        r#"// Code generated by l10n4x-toolkit. DO NOT EDIT.
import {{ writable, derived }} from 'svelte/store'
import {{
  t as coreT,
  loadLocale,
  initializeI18n,
}} from './generated'

const FALLBACK_LOCALE = "{fallback}"

export type LocaleKey =
{keys}

export const locale = writable<string>(FALLBACK_LOCALE)
export const isReady = writable<boolean>(false)
export const currentLocale = derived(locale, ($locale) => $locale)

export function t(key: LocaleKey, params?: Record<string, string | number>) {{
  let $locale: string
  locale.subscribe((v) => ($locale = v))()
  return coreT($locale, key, params)
}}

export async function setLocale(loc: string) {{
  await loadLocale(loc)
  locale.set(loc)
  isReady.set(true)
}}

export async function initI18n(loc = FALLBACK_LOCALE) {{
  await initializeI18n()
  await setLocale(loc)
}}
"#,
        keys = key_definitions,
        fallback = ctx.fallback,
    );

    let file_path = out_dir.join("i18n.ts");
    fs::write(&file_path, content)?;
    println!("Generated Svelte stores at '{}'", file_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::targets::GenerateContext;
    use std::collections::HashMap;

    fn test_ctx() -> GenerateContext<'static> {
        GenerateContext {
            fallback: "en",
            output_dir: "",
            source_dir: "",
            verify_key_bytes: "000000000000000000000000000000000000000000000000000000000000000000",
            verify_public_key_hex: "",
            encrypt: false,
            encrypt_key_env: "",
        }
    }

    #[test]
    fn generates_svelte_stores() {
        let dir = tempfile::tempdir().unwrap();
        let sorted: Vec<String> = vec!["welcome.title".to_string()];
        let params = HashMap::new();
        generate(dir.path(), &sorted, &Value::Null, &test_ctx(), &params).unwrap();
        let content = std::fs::read_to_string(dir.path().join("i18n.ts")).unwrap();
        assert!(content.contains("export const locale"));
        assert!(content.contains("welcome.title"));
    }

    #[test]
    fn generates_multiple_keys() {
        let dir = tempfile::tempdir().unwrap();
        let sorted: Vec<String> = vec!["a.b".to_string(), "c.d".to_string()];
        let params = HashMap::new();
        generate(dir.path(), &sorted, &Value::Null, &test_ctx(), &params).unwrap();
        let content = std::fs::read_to_string(dir.path().join("i18n.ts")).unwrap();
        assert!(content.contains("a.b"));
        assert!(content.contains("c.d"));
        assert!(content.contains("LocaleKey"));
    }
}
