use crate::targets::GenerateContext;
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

pub fn generate(
    out_dir: &Path,
    key_pairs: &[(u64, String)],
    _options: &Value,
    ctx: &GenerateContext<'_>,
    _params_map: &HashMap<String, Vec<String>>,
) -> Result<(), anyhow::Error> {
    let mut key_definitions = String::new();
    for (hash, name) in key_pairs {
        let pascal_name = crate::generator::to_pascal_case(name);
        key_definitions.push_str(&format!("export const {} = 0x{:016x} as const;\n", pascal_name, hash));
    }

    let content = format!(
        r#"// Code generated by l10n4x-toolkit. DO NOT EDIT.
import {{ writable, derived }} from 'svelte/store'
import {{
  t as coreT,
  loadLocale,
  initializeI18n,
}} from './generated'

const FALLBACK_LOCALE = "{fallback}"

export type LocaleKey = number

{keys}
export const locale = writable<string>(FALLBACK_LOCALE)
export const isReady = writable<boolean>(false)
export const currentLocale = derived(locale, ($locale) => $locale)

export function t(key: LocaleKey, params?: Record<string, string | number>) {{
  let $locale: string
  locale.subscribe((v) => ($locale = v))()
  return coreT($locale, key, params)
}}

export async function setLocale(loc: string) {{
  await loadLocale(loc)
  locale.set(loc)
  isReady.set(true)
}}

export async function initI18n(loc = FALLBACK_LOCALE) {{
  await initializeI18n()
  await setLocale(loc)
}}
"#,
        keys = key_definitions,
        fallback = ctx.fallback,
    );

    let file_path = out_dir.join("i18n.ts");
    fs::write(&file_path, content)?;
    println!("Generated Svelte stores at '{}'", file_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::targets::GenerateContext;
    use std::collections::HashMap;

    fn test_ctx() -> GenerateContext<'static> {
        GenerateContext {
            fallback: "en",
            output_dir: "",
            source_dir: "",
            verify_key_bytes: "000000000000000000000000000000000000000000000000000000000000000000",
            verify_public_key_hex: "",
            encrypt: false,
            encrypt_key_env: "",
        }
    }

    #[test]
    fn generates_svelte_stores() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![(0xabcdef0123456789, "welcome.title".to_string())];
        let params = HashMap::new();
        generate(dir.path(), &key_pairs, &Value::Null, &test_ctx(), &params).unwrap();
        let content = std::fs::read_to_string(dir.path().join("i18n.ts")).unwrap();
        assert!(content.contains("export const locale"));
        assert!(content.contains("export const WelcomeTitle = 0xabcdef0123456789 as const;"));
    }

    #[test]
    fn generates_multiple_keys() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![
            (0xabcdef0123456789, "a.b".to_string()),
            (0x123456789abcdef0, "c.d".to_string()),
        ];
        let params = HashMap::new();
        generate(dir.path(), &key_pairs, &Value::Null, &test_ctx(), &params).unwrap();
        let content = std::fs::read_to_string(dir.path().join("i18n.ts")).unwrap();
        assert!(content.contains("export const AB = 0xabcdef0123456789 as const;"));
        assert!(content.contains("export const CD = 0x123456789abcdef0 as const;"));
        assert!(content.contains("LocaleKey"));
    }
}
