use crate::targets::GenerateContext;
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

pub fn generate(
    out_dir: &Path,
    key_pairs: &[(u64, String)],
    _options: &Value,
    ctx: &GenerateContext<'_>,
    _params_map: &HashMap<String, Vec<String>>,
) -> Result<(), anyhow::Error> {
    let mut key_definitions = String::new();
    for (hash, name) in key_pairs {
        let pascal_name = crate::generator::to_pascal_case(name);
        key_definitions.push_str(&format!("export const {} = 0x{:016x} as const;\n", pascal_name, hash));
    }

    let content = format!(
        r#"// Code generated by l10n4x-toolkit. DO NOT EDIT.
import {{ ref, onMounted }} from 'vue'
import {{
  t as coreT,
  loadLocale,
  initializeI18n,
}} from './generated'

const FALLBACK_LOCALE = "{fallback}"

export type LocaleKey = number

{keys}
export function useI18n(initialLocale = FALLBACK_LOCALE) {{
  const locale = ref(initialLocale)
  const isReady = ref(false)

  async function setLocale(loc: string) {{
    await loadLocale(loc)
    locale.value = loc
    isReady.value = true
  }}

  function t(key: LocaleKey, params?: Record<string, string | number>) {{
    return coreT(locale.value, key, params)
  }}

  onMounted(async () => {{
    await initializeI18n()
    await setLocale(initialLocale)
  }})

  return {{ t, locale, setLocale, isReady }}
}}
"#,
        keys = key_definitions,
        fallback = ctx.fallback,
    );

    let file_path = out_dir.join("useI18n.ts");
    fs::write(&file_path, content)?;
    println!("Generated Vue bindings at '{}'", file_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::targets::GenerateContext;
    use std::collections::HashMap;

    fn test_ctx() -> GenerateContext<'static> {
        GenerateContext {
            fallback: "en",
            output_dir: "",
            source_dir: "",
            verify_key_bytes: "000000000000000000000000000000000000000000000000000000000000000000",
            verify_public_key_hex: "",
            encrypt: false,
            encrypt_key_env: "",
        }
    }

    #[test]
    fn generates_vue_composable() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![(0xabcdef0123456789, "welcome.title".to_string())];
        let params = HashMap::new();
        generate(dir.path(), &key_pairs, &Value::Null, &test_ctx(), &params).unwrap();
        let content = std::fs::read_to_string(dir.path().join("useI18n.ts")).unwrap();
        assert!(content.contains("useI18n"));
        assert!(content.contains("export const WelcomeTitle = 0xabcdef0123456789 as const;"));
    }

    #[test]
    fn generates_locale_key_type() {
        let dir = tempfile::tempdir().unwrap();
        let key_pairs: Vec<(u64, String)> = vec![
            (0xabcdef0123456789, "a.b".to_string()),
            (0x123456789abcdef0, "c.d".to_string()),
        ];
        let params = HashMap::new();
        generate(dir.path(), &key_pairs, &Value::Null, &test_ctx(), &params).unwrap();
        let content = std::fs::read_to_string(dir.path().join("useI18n.ts")).unwrap();
        assert!(content.contains("export const AB = 0xabcdef0123456789 as const;"));
        assert!(content.contains("export const CD = 0x123456789abcdef0 as const;"));
        assert!(content.contains("LocaleKey"));
    }
}
