name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [ checks_requested ]

permissions:
  contents: read

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411  # v2
        with:
          egress-policy: audit
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: dtolnay/rust-toolchain@67ef31d5b988238dd797d409d6f9574278e20537  # master
        with:
          toolchain: stable
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@23869a5bd66c73db3c0ac40331f3206eb23791dc  # v2.9.1
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --locked
      - name: Generate coverage report
        run: cargo tarpaulin --workspace --all-features --out xml --timeout 300 -- --test-threads=1
      - name: Upload to codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
